{% set version = "2.3.0" %}

package:
  name: libsbol
  version: {{ version }}

source:
    git_url: https://github.com/jlv100/libSBOL.git
    git_rev: cmake_icase

build:
  number: 1

  run_exports:
    - libsbol

requirements:
  host:
    - python=3.5
    - raptor
    - rasqal
    - libiconv
  build:
    - make
    - cmake=3.12.4
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - jsoncpp
    - pkg-config
    - ripgrep
  run:
    - libgcc
    - libgcc-ng
    - libstdcxx-ng
    - libxslt
    - libcurl
    - jsoncpp
    - raptor
    - rasqal 
    - icu=58

test:
  imports:
    - sbol
  commands:
    - python -m unittest sbol.unit_tests

about:
  home: http://synbiodex.github.io/libSBOL
  license: Apache2
  summary: 'Synthetic Biology Open Language'
  description: 'libSBOL is a C++ library for reading, writing, and constructing genetic designs according to the standardized specifications of the Synthetic Biology Open Language (SBOL).'
  dev_url: https://github.com/jlv100/libSBOL
  doc_url: https://github.com/jlv100/libSBOL
  doc_source_url: https://github.com/jlv100/libSBOL/blob/cmake_icase/README.md

